

<!--
var win,openWin;
function openWin(url){

	if( win && !win.closed ){
		win.location = url;
		win.focus();
	}else{
		win = window.open(url,"Sample","toolbar=no,statusbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=420,height=450,left=0,top=0");
	}
}



<!--
var win,openWin;
function openWin1(url){

	if( win && !win.closed ){
		win.location = url;
		win.focus();
	}else{
		win = window.open(url,"Sample","toolbar=no,statusbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=420,height=530,left=0,top=0");
	}
}
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->



<!--
var win,openWin;
function openWin2(url){

	if( win && !win.closed ){
		win.location = url;
		win.focus();
	}else{
		win = window.open(url,"Sample","toolbar=no,statusbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=378,height=150,left=0,top=0");
	}
}
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->



<!--
var win,openWin;
function openWin4(url){

	if( win && !win.closed ){
		win.location = url;
		win.focus();
	}else{
		win = window.open(url,"Sample2","toolbar=no,statusbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=420,height=190,left=0,top=0");
	}
}




<!--
var win,openWin;
function openWin5(url){

	if( win && !win.closed ){
		win.location = url;
		win.focus();
	}else{
		win = window.open(url,"Sample2","toolbar=no,statusbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=445,height=280,left=0,top=0");
	}
}



<!--
var win,openWin;
function openWin3(url){

	if( win && !win.closed ){
		win.location = url;
		win.focus();
	}else{
		win = window.open(url,"Sample","toolbar=no,statusbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=400,height=225,left=0,top=0");
	}
}





<!--
var win,openWin;
function openWin6(url){

	if( win && !win.closed ){
		win.location = url;
		win.focus();
	}else{
		win = window.open(url,"Sample","toolbar=no,statusbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=420,height=550,left=0,top=0");
	}
}




<!-- Begin
function right(e) {
if (navigator.appName == 'Netscape' && 
(e.which == 3 || e.which == 2))
return false;
else if (navigator.appName == 'Microsoft Internet Explorer' && 
(event.button == 2 || event.button == 3)) {
alert("Sorry, you do not have permission to right click.");
return false;
}
return true;
}

document.onmousedown=right;
if (document.layers) window.captureEvents(Event.MOUSEDOWN);
window.onmousedown=right;
//  End -->





<!--
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v3.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->





